# Note: these are GNU find patterns, so "*" has no special behavior for directory separators


## /boot

# Boot binaries
IgnorePath "/boot/*.img"
IgnorePath "/boot/vmlinuz-*"
# Case-insensitive to match the fallback /boot/EFI/BOOT/BOOTX64.EFI
IgnorePath "/boot/*.[eE][fF][iI]"

# Auto-generated bootloader files
IgnorePath "/boot/loader/entries.srel"
IgnorePath "/boot/loader/random-seed"


## /etc

# Auto-generated config files
IgnorePath "/etc/.pwd.lock"
IgnorePath "/etc/.updated"
IgnorePath "/etc/adjtime"
IgnorePath "/etc/group-"
IgnorePath "/etc/gshadow-"
IgnorePath "/etc/ld.so.cache"
# Technically, this is supposed to be persistent and confidential, but I don't use it for anything, so it should be fine to let systemd regenerate it if needed
IgnorePath "/etc/machine-id"
IgnorePath "/etc/os-release"
IgnorePath "/etc/pacman.d/gnupg/*"
# Generated by reflector
IgnorePath "/etc/pacman.d/mirrorlist"
IgnorePath "/etc/passwd-"
IgnorePath "/etc/shadow-"
# Managed by package install scripts
IgnorePath "/etc/shells"
IgnorePath "/etc/subuid-"
IgnorePath "/etc/subgid-"

# Auto-generated SSL certificates
IgnorePath "/etc/ca-certificates/extracted/*"
IgnorePath "/etc/ssl/certs/*"

# User/group passwords
# TODO: store these safely
IgnorePath "/etc/gshadow"
IgnorePath "/etc/shadow"

# Wi-Fi passwords
# TODO: store these safely as well
IgnorePath "/etc/NetworkManager/system-connections/*"

# TODO: contains some sensitive information, store this safely
IgnorePath "/etc/resolv.conf"

# TODO: contains disk UUIDs, not sensitive but need to be made generic because they are completely machine-specific
IgnorePath "/etc/fstab"
IgnorePath "/boot/loader/entries/*"

## /usr

# Auto-generated files
IgnorePath "/usr/lib/locale/locale-archive"
IgnorePath "/usr/lib/modules/*"
IgnorePath "/usr/lib/udev/hwdb.bin"
IgnorePath "/usr/share/info/dir"

# Files with properties automatically modified
IgnorePath "/usr/bin/groupmems"


## /var

# Auto-generated files
IgnorePath "/var/.updated"
# Persistent program state information - not sure about completely ignoring this
IgnorePath "/var/lib/*"

# Pacman database
IgnorePath "/var/lib/pacman/local/*"
IgnorePath "/var/lib/pacman/sync/*"

# Logs and temporary files
IgnorePath "/var/log/*"
IgnorePath "/var/tmp/*"
