# Note: these are GNU find patterns, so "*" has no special behavior for directory separators


## /boot

# Boot binaries
IgnorePath "/boot/*.img"
IgnorePath "/boot/vmlinuz-*"
# Case-insensitive to match the fallback /boot/EFI/BOOT/BOOTX64.EFI
IgnorePath "/boot/*.[eE][fF][iI]"

# Auto-generated bootloader files
IgnorePath "/boot/loader/entries.srel"
IgnorePath "/boot/loader/random-seed"


## /etc

# Auto-generated config files
IgnorePath "/etc/.pwd.lock"
IgnorePath "/etc/.updated"
IgnorePath "/etc/adjtime"
IgnorePath "/etc/group-"
IgnorePath "/etc/gshadow-"
IgnorePath "/etc/ld.so.cache"
# Technically, this is supposed to be persistent and confidential, but I don't use it for anything, so it should be fine to let systemd regenerate it if needed
IgnorePath "/etc/machine-id"
IgnorePath "/etc/os-release"
IgnorePath "/etc/pacman.d/gnupg/*"
# Generated by reflector
IgnorePath "/etc/pacman.d/mirrorlist"
IgnorePath "/etc/passwd-"
IgnorePath "/etc/shadow-"
# Managed by package install scripts
IgnorePath "/etc/shells"
IgnorePath "/etc/subuid-"
IgnorePath "/etc/subgid-"

# Auto-generated SSL certificates
IgnorePath "/etc/ca-certificates/extracted/*"
IgnorePath "/etc/ssl/certs/*"

# Unnecessary parts of NetworkManager connections that can be safely regenerated on new systems
function NetworkManagerConnectionFilter() {
    grep --invert-match --extended-regexp "^(timestamp|uuid)="
}
AddFileContentFilter "/etc/NetworkManager/system-connections/*.nmconnection" NetworkManagerConnectionFilter


## /usr

# Auto-generated files
IgnorePath "/usr/lib/gdk-pixbuf-*/loaders.cache"
IgnorePath "/usr/lib/gio/modules/giomodule.cache"
IgnorePath "/usr/lib/gtk-*/immodules.cache"
IgnorePath "/usr/lib/locale/locale-archive"
IgnorePath "/usr/lib/modules/*"
IgnorePath "/usr/lib/udev/hwdb.bin"
IgnorePath "/usr/lib/utempter/utempter"
IgnorePath "/usr/lib/vlc/plugins/plugins.dat"
IgnorePath "/usr/share/applications/mimeinfo.cache"
IgnorePath "/usr/share/glib-2.0/schemas/gschemas.compiled"
IgnorePath "/usr/share/icons/*/icon-theme.cache"
IgnorePath "/usr/share/info/dir"
IgnorePath "/usr/share/mime/*"

# Files with properties automatically modified
IgnorePath "/usr/bin/groupmems"

# Secure-Boot-signed systemd-boot files (managed by sbctl)
IgnorePath "/usr/lib/systemd/boot/efi/*.signed"

## /var

# Auto-generated files
IgnorePath "/var/.updated"

# Unnecessary program state information
IgnorePath "/var/lib/dbus/*"
IgnorePath "/var/lib/iwd/*"
IgnorePath "/var/lib/lastlog/*"
IgnorePath "/var/lib/libuuid/*"
IgnorePath "/var/lib/machines/*"
IgnorePath "/var/lib/NetworkManager/*"
IgnorePath "/var/lib/plocate/CACHEDIR.TAG"
IgnorePath "/var/lib/plocate/plocate.db"
IgnorePath "/var/lib/plymouth/boot-duration"
IgnorePath "/var/lib/portables/*"
IgnorePath "/var/lib/private/*"
IgnorePath "/var/lib/sddm/*"
IgnorePath "/var/lib/systemd/*"
IgnorePath "/var/lib/fwupd/*"
IgnorePath "/var/lib/passim/*"
IgnorePath "/var/lib/tpm2-tss/*"

# Secure Boot keys should be unique per device, and it would honestly be easier to just regenerate them and reset the UEFI back to setup mode than store them safely
IgnorePath "/var/lib/sbctl/GUID"
IgnorePath "/var/lib/sbctl/keys/*"

# Pacman database
IgnorePath "/var/lib/pacman/local/*"
IgnorePath "/var/lib/pacman/sync/*"

# Logs and temporary files
IgnorePath "/var/log/*"
IgnorePath "/var/tmp/*"


## Other

# Swapfile
# TODO: not declarative
IgnorePath "/swap/swapfile"
