# CLI programs

# Bash tab completion beyond just files
AddPackage bash-completion

# Not my primary editor but can be useful
AddPackage vim

# Safely trash files
AddPackage trash-cli

# SSH
AddPackage openssh

# Matt Daemon
CopyFile /etc/systemd/system/matt.service
CreateLink /etc/systemd/system/multi-user.target.wants/matt.service /etc/systemd/system/matt.service

# Find added files not managed by pacman
AddPackage lostfiles

lostfiles_conf="$(CreateFile /etc/lostfiles.conf)"
cat > "$lostfiles_conf" <<EOF
+/

# Note: automatically generated by aconfmgr
EOF

# Reuse previously-defined aconfmgr ignored paths for lostfiles by using an internal aconfmgr function
AconfCreateFindIgnoreArgs lostfiles_ignore_args "${ignore_paths[@]}"

# Quote each argument to avoid syntax errors from lostfiles, which reads the file using readarray
quoted_lostfiles_ignore_args=""
for lostfiles_arg in "${lostfiles_ignore_args[@]}"; do
    quoted_lostfiles_ignore_args+="\"$lostfiles_arg\" "
done

# See /usr/lib/aconfmgr/common.bash, search for "sudo find /"
echo "\$-regextype posix-extended -not \\( \\( $quoted_lostfiles_ignore_args\\) -prune \\) -print" >>"$lostfiles_conf"

# CTags: used by several Kate plugins for code navigation
AddPackage ctags

# Syncthing
AddPackage syncthing
